spring:
  application:
    name: assignment-portal
  data:
    mongodb:
      uri: mongodb+srv://<mongo_username>:<mongo_password>@samplecluster.ff5e4qb.mongodb.net/<database_name>?retryWrites=true&w=majority&appName=SampleCluster
  security:
    user:
      name: username
      password: password